export const slides = [
  {
    image: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Booket/Top+Banner.webp`,
    alt: 'Design Slide 1',
  },
  {
    image: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/munch+tantra/Top+Banner.webp`,
    alt: 'Design Slide 2',
  },
  {
    image: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Project+3-+MTR/banner+image.webp`,
    alt: 'Design Slide 3',
  },
  {
    image: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Project+3+-+Revolutionari+Awards/RE-Awards-Banner.webp`,
    alt: 'Design Slide 4',
  },
  {
    image: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/DRL+Report/DRL-Banner.webp`,
    alt: 'Design Slide 5',
  },
];

export const tabs = [
  { id: 'Spotlighted', label: 'Spotlighted' },
  { id: 'Brand-identity', label: 'Brand Identity' },
  { id: 'Environmental-graphic', label: 'Environment Graphics' },
  { id: 'Book-design', label: 'Book Design' },
  { id: 'Event-design', label: 'Event Design' },
  { id: 'Campaigns', label: 'Campaigns' },
  { id: 'Film-Motion-Graphics', label: 'Film & Motion Graphics' },
  { id: 'Product', label: 'Product' },
];

export const portfolioItems = {
  "Spotlighted" : [
    {
      id: 'lendersmark',
      title: 'LendersMark',
      description: 'Description A4',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-05.webp`,
      link: '/projects/lendersmark',
    },
    {
      id: 'mtr',
      title: 'Mera Terah Run',
      description: 'Description A5',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-19.webp`,
      link: '/projects/mtr',
    },
    {
      id: 'drlreport',
      title: 'DRL Report',
      description: 'Inspire description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-16.webp`,
      link: '/projects/drlreport',
    },
    {
      id: 'kyoorius',
      title: 'Kyoorius',
      description: 'Inspire description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-14.webp`,
      link: '/projects/kyoorius',
    },
    {
      id: 'kheemasutra',
      title: 'Kheemasutra',
      description: 'Description A7',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/kheemasutra+thumbnail.webp`,
      link: '/projects/kheemasutra',
    },
    {
      id: 'munchatantra',
      title: 'Munchatantra',
      description: 'Description A1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-21.webp`,
      link: '/projects/munchatantra',
    },
  ],
  "Brand-identity" : [
    {
      id: 'munchatantra-brand',
      title: 'Munchatantra',
      description: 'Description A1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-21.webp`,
      link: '/projects/munchatantra',
    },
    {
      id: 'seafund',
      title: 'Seafund',
      description: 'Description A2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Seafund/thumbnail.webp`,
      link: '/projects/seafund',
    },
    {
      id: 'bsf',
      title: 'BSF',
      description: 'Description A3',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-09.webp`,
      link: '/projects/bsf',
    },
    {
      id: 'lendersmark-brand',
      title: 'LendersMark',
      description: 'Description A4',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-05.webp`,
      link: '/projects/lendersmark',
    },
    {
      id: 'mtr-brand',
      title: 'Mera Terah Run',
      description: 'Description A5',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-19.webp`,
      link: '/projects/mtr',
    },
    {
      id: 'dhool',
      title: 'Dhool',
      description: 'Description A6',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/dhool+thumbnail.webp`,
      link: '/projects/dhool',
    },
    {
      id: 'kheemasutra-brand',
      title: 'Kheemasutra',
      description: 'Description A7',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/kheemasutra+thumbnail.webp`,
      link: '/projects/kheemasutra',
    },
    {
      id: 'kachumbar',
      title: 'Kachumbar',
      description: 'Description A8',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Kachumbar/Thumbnail-kachumbar.webp`,
      link: '/projects/kachumbar',
    },
    {
      id: 'karnataka',
      title: 'Karnataka',
      description: 'Description A9',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-10.webp`,
      link: '/projects/karnataka',
    },
    {
      id: 'mypreciousgens',
      title: 'Mypreciousgens',
      description: 'Description A10',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/preciousgenes/MPG+thumbnail.png`,
      link: '/projects/genes',
    },
  ],
  "Environmental-graphic" : [
    {
      id: 'akamai',
      title: 'Akamai',
      description: 'Creative description line 1.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-20.webp`,
      link: '/projects/akamai',
    },
    {
      id: 'kosi',
      title: 'Kosi',
      description: 'Creative description line 2.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-11.webp`,
      link: '/projects/kosi',
    },
    {
      id: 'munchatantra-env',
      title: 'Munchatantra',
      description: 'Creative description line 1.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-21.webp`,
      link: '/projects/munchatantra',
    },
    {
      id: 'decathalon',
      title: 'Decathalon',
      description: 'Creative description line 2.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/decathlon/thumbnail.webp`,
      link: '/projects/decathalon',
    },
    {
      id: 'nauvata',
      title: 'Nauvata',
      description: 'Creative description line 1.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/NAUVATA.webp`,
      link: '/projects/nauvata',
    },
    {
      id: 'vmware',
      title: 'VMWare',
      description: 'Creative description line 2.',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/VM+WARE.webp`,
      link: '/projects/vmware',
    },
  ],
  "Book-design" : [
    {
      id: 'drlreport-book',
      title: 'DRL Report',
      description: 'Inspire description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-16.webp`,
      link: '/projects/drlreport',
    },
    {
      id: 'kyoorius-book',
      title: 'Kyoorius',
      description: 'Inspire description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-14.webp`,
      link: '/projects/kyoorius',
    },
    {
      id: 'kdem',
      title: 'KDEM Report',
      description: 'Inspire description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-03.webp`,
      link: '/projects/kdem',
    },
    {
      id: 'shopperstop',
      title: 'Shoppers Stop',
      description: 'Inspire description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Project+3+-+Shopper's+Stop/shoppers+stop+thumbnail.webp`,
      link: '/projects/shopperstop',
    },
  ],
  "Event-design" : [
    {
      id: 'levis',
      title: 'Levis x appeal',
      description: 'Vision description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-04.webp`,
      link: '/projects/levis',
    },
    {
      id: 'sapgca',
      title: 'SAP GCA',
      description: 'Vision description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-07.webp`,
      link: '/projects/sapgca',
    },
    {
      id: 'sn',
      title: 'SN Cures',
      description: 'Vision description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-17.webp`,
      link: '/projects/sn',
    },
    {
      id: 'revolutionari',
      title: 'Revolutionari',
      description: 'Vision description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-12.webp`,
      link: '/projects/revolutionari',
    },
    {
      id: 'pepsico',
      title: 'PepsiCo Assam',
      description: 'Vision description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/pepsico-assam/thumbnail.webp`,
      link: '/projects/pepsico',
    },
  ],
  "Campaigns" : [
    {
      id: 'nandoos',
      title: 'Nandoos',
      description: 'Identity description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-15.webp`,
      link: '/projects/nandoos',
    },
    {
      id: 'revolutionari-campaign',
      title: 'Revolutionari',
      description: 'Identity description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-12.webp`,
      link: '/projects/revolutionari',
    },
    {
      id: 'fmr',
      title: 'FMR',
      description: 'Identity description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/FMR+thumbnail.webp`,
      link: '/projects/fmr',
    },
    {
      id: 'decathalon-campaign',
      title: 'Decathalon',
      description: 'Identity description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/decathlon/thumbnail.webp`,
      link: '/projects/decathalon',
    },
  ],
  "Film-Motion-Graphics" : [
    {
      id: 'quaker',
      title: 'Quaker-Bowl of growth',
      description: 'Essence description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-01.webp`,
      link: '/projects/quaker',
    },
    {
      id: 'practo',
      title: 'Practo',
      description: 'Essence description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-22.webp`,
      link: '/projects/practo',
    },
    {
      id: 'canara',
      title: 'Canara Bank',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/thumbnails/canara+bank+thumbnail'.webp`,
      link: '/projects/canara',
    },
    {
      id: 'dilsenaman',
      title: 'Dil se Naman',
      description: 'Essence description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/Dilsenaman/thumbnail.webp`,
      link: '/projects/dilsenaman',
    },
    {
      id: 'vbl',
      title: 'VBL',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/VBL+ESG/thumbnail.webp`,
      link: '/projects/vbl',
    },
    {
      id: 'swiggy',
      title: 'Swiggy',
      description: 'Essence description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/swiggy+champions/thumbnail.webp`,
      link: '/projects/swiggy',
    },
    {
      id: 'skf',
      title: 'SKF',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/SKF/tumbnail.webp`,
      link: '/projects/skf',
    },
    {
      id: 'sap',
      title: 'SAP 25 years',
      description: 'Essence description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/SAP/thumbnail.webp`,
      link: '/projects/sap',
    },
    {
      id: 'pepsico-film',
      title: 'PepsiCo Assam',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/pepsico-assam/thumbnail.webp`,
      link: '/projects/pepsico',
    },
    {
      id: 'pepsicoKosi',
      title: 'PepsiCo Kosi film',
      description: 'Essence description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/pepsico+kosi+film/thumbnail.webp`,
      link: '/projects/pepsicoKosi',
    },
    {
      id: 'lam',
      title: 'LAM Event',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/LAM+event/thumbnail.webp`,
      link: '/projects/lam',
    },
    {
      id: 'docmydoc',
      title: 'Doc My Doc',
      description: 'Essence description Y',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/docmydoc/thumbnail.webp`,
      link: '/projects/docmydoc',
    },
    {
      id: 'levisxappeal',
      title: 'Levi\'s X Appeal',
      description: 'Essence description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/X-Appeal/thumbnail.webp`,
      link: '/projects/levisxappeal',
    },
  ],
  "Product" : [
    {
      id: 'booket',
      title: 'Booket',
      description: 'Product description 1',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-02.webp`,
      link: '/projects/booket',
    },
    {
      id: 'terralite',
      title: 'Teralite',
      description: 'Product description 2',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Project-Images/terralite/thumbnail.webp`,
      link: '/projects/terralite',
    },
    {
      id: 'munchatantra-product',
      title: 'Munchatantra',
      description: 'Product description X',
      imageUrl: `https://veeville-website.s3.ap-south-1.amazonaws.com/Images/Work+page-Thumbnails/1-21.webp`,
      link: '/projects/munchatantra',
    },
  ],
}